### ISSUE TITLE
no file

### ISSUE THREAD

**Issue by Misha279-UA** [Wehrmachtserdbeere/MDRG-Analyzer#4]
i can't find save folder
(And app in 1.1.1 folder still 1.1.0)

**Comment by Wehrmachtserdbeere** [comment]
It says in the Readme where the folder is now. It is in `C:\Users\USER\AppData\LocalLow\IncontinentCell\My Dystopian Robot Girlfriend\Saves`

**Comment by Misha279-UA** [comment]
still can't find, mayby i download somesing wrong, but app reley don't work: it say it not latest wersion (but folder name is 1.1.1)
![image](https://github.com/Wehrmachtserdbeere/MDRG-Analyzer/assets/156463244/69719818-01e9-4a4b-8ce2-92e0a026ef56)
i can't find save folder, it haven't README

**Comment by Wehrmachtserdbeere** [comment]
That text is a small oversight, I'll quickly upload a fix for it and it'll be fixed in the next release. The save folder is in `C:\Users\USER\AppData\LocalLow\IncontinentCell\My Dystopian Robot Girlfriend\Saves`. Please look up how to find your AppData folder if you haven't already. If the save isn't there, you can follow the next part of the ReadMe, which tells you to go into the Main Menu, press "Load", press "To File", then load that file.

**Comment by Misha279-UA** [comment]
maybay it I stupid, and can't find correct wersion, but i go to releases, latest 1.1.1, but after downloading it still "have new version" and other issues had before.
i have no any idea what to do.
(and i use it in 0.86 and it work  so idk)
